version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: flagship-postgres
    environment:
      POSTGRES_USER: flagship
      POSTGRES_PASSWORD: flagship
      POSTGRES_DB: flagship
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: flagship-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:

